services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5430:5432
    platform: linux/amd64
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 10s
      retries: 5

  api:
    build:
      context: .
      dockerfile: ./src/server/docker/Dockerfile.local
    environment:
      NODE_ENV: development
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
      TZ: ${TZ}
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    ports:
      - 3015:3005
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: ./src/client/docker/Dockerfile.local
    environment:
      NODE_ENV: development
      TZ: ${TZ}
    volumes:
      - ./src:/app/src
    ports:
      - 5175:5173

volumes:
  db-data:
